#!/usr/bin/env bash
#python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_101_FPN_baseline.yaml" MODEL.ROI_BOX_HEAD.USE_GIOU True OUTPUT_DIR "results/giou_box/faster_v"
#python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_50_FPN_all.yaml" MODEL.ROI_BOX_HEAD.USE_GIOU True OUTPUT_DIR "results/giou_box/faster_v_all"
#python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_101_FPN_baseline.yaml" MODEL.WEIGHTS "https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x/137260431/model_final_a54504.pkl" MODEL.MASK_ON True MODEL.ROI_BOX_HEAD.USE_GIOU True OUTPUT_DIR "results/giou_box/mask_v"
#python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_50_FPN_all.yaml" MODEL.WEIGHTS "https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x/137260431/model_final_a54504.pkl" MODEL.MASK_ON True MODEL.ROI_BOX_HEAD.USE_GIOU True OUTPUT_DIR "results/giou_box/mask_v_all"
#
#python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_101_FPN_baseline.yaml" MODEL.RPN.USE_GIOU True OUTPUT_DIR "results/giou_rpn/faster_v"
#python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_50_FPN_all.yaml" MODEL.RPN.USE_GIOU True OUTPUT_DIR "results/giou_rpn/faster_v_all"
#python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_101_FPN_baseline.yaml" MODEL.WEIGHTS "https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x/137260431/model_final_a54504.pkl" MODEL.MASK_ON True MODEL.RPN.USE_GIOU True OUTPUT_DIR "results/giou_rpn/mask_v"
#python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_50_FPN_all.yaml" MODEL.WEIGHTS "https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x/137260431/model_final_a54504.pkl" MODEL.MASK_ON True MODEL.RPN.USE_GIOU True OUTPUT_DIR "results/giou_rpn/mask_v_all"

#python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_101_FPN_baseline.yaml" MODEL.RPN.USE_GIOU True MODEL.ROI_BOX_HEAD.USE_GIOU True OUTPUT_DIR "results/giou_both/faster_v"
#python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_50_FPN_all.yaml" MODEL.RPN.USE_GIOU True MODEL.ROI_BOX_HEAD.USE_GIOU True OUTPUT_DIR "results/giou_both/faster_v_all"
#python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_101_FPN_baseline.yaml" MODEL.WEIGHTS "https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x/137260431/model_final_a54504.pkl" MODEL.MASK_ON True MODEL.RPN.USE_GIOU True MODEL.ROI_BOX_HEAD.USE_GIOU True OUTPUT_DIR "results/giou_both/mask_v"
#python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_50_FPN_all.yaml" MODEL.WEIGHTS "https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x/137260431/model_final_a54504.pkl" MODEL.MASK_ON True MODEL.RPN.USE_GIOU True MODEL.ROI_BOX_HEAD.USE_GIOU True OUTPUT_DIR "results/giou_both/mask_v_all"

#python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_101_FPN_baseline.yaml" MODEL.ROI_BOX_HEAD.USE_GIOU True OUTPUT_DIR "results/giou/l1_1giou" MODEL.ROI_HEADS.LOSS_WEIGHTS   "(1.0,1.0,1.0)"
#python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_101_FPN_baseline.yaml" MODEL.ROI_BOX_HEAD.USE_GIOU True OUTPUT_DIR "results/giou/05l1_1giou" MODEL.ROI_HEADS.LOSS_WEIGHTS "(0.5,1.0,1.0)"
#python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_101_FPN_baseline.yaml" MODEL.ROI_BOX_HEAD.USE_GIOU True OUTPUT_DIR "results/giou/0l1_1giou" MODEL.ROI_HEADS.LOSS_WEIGHTS  "(0.0,1.0,1.0)"
#python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_101_FPN_baseline.yaml" MODEL.ROI_BOX_HEAD.USE_GIOU True OUTPUT_DIR "results/giou/1l1_05giou" MODEL.ROI_HEADS.LOSS_WEIGHTS "(1.0,0.5,1.0)"


python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_101_FPN_baseline.yaml" OUTPUT_DIR "results/results/giou/wce" TEST.DETECTIONS_PER_IMAGE 3 DATASETS.TEST "('CVC_ColonDB', 'CVC_ClinicDB', 'ETIS_LaribPolypDB', 'CVC_VideoClinicDB_test', 'CVC_VideoClinicDB_valid')" MODEL.ROI_HEADS.LOSS_WEIGHTS   "(1.0,1.0,1.0)" MODEL.ROI_HEADS.WCE_LOSS True
python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_101_FPN_baseline.yaml" OUTPUT_DIR "results/results/giou/giou" TEST.DETECTIONS_PER_IMAGE 3 DATASETS.TEST "('CVC_ColonDB', 'CVC_ClinicDB', 'ETIS_LaribPolypDB', 'CVC_VideoClinicDB_test', 'CVC_VideoClinicDB_valid')" MODEL.ROI_HEADS.LOSS_WEIGHTS   "(0.0,1.0,1.0)" MODEL.ROI_BOX_HEAD.USE_GIOU True
python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_101_FPN_baseline.yaml" OUTPUT_DIR "results/results/giou/ciou" TEST.DETECTIONS_PER_IMAGE 3 DATASETS.TEST "('CVC_ColonDB', 'CVC_ClinicDB', 'ETIS_LaribPolypDB', 'CVC_VideoClinicDB_test', 'CVC_VideoClinicDB_valid')" MODEL.ROI_HEADS.LOSS_WEIGHTS   "(0.0,1.0,1.0)" MODEL.ROI_BOX_HEAD.USE_CIOU True
python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_101_FPN_baseline.yaml" OUTPUT_DIR "results/results/giou/giou_05l1" TEST.DETECTIONS_PER_IMAGE 3 DATASETS.TEST "('CVC_ColonDB', 'CVC_ClinicDB', 'ETIS_LaribPolypDB', 'CVC_VideoClinicDB_test', 'CVC_VideoClinicDB_valid')" MODEL.ROI_HEADS.LOSS_WEIGHTS   "(0.5,1.0,1.0)" MODEL.ROI_BOX_HEAD.USE_GIOU True
python tools/train_net.py --config-file "configs/polyp/baselines/faster_R_101_FPN_baseline.yaml" OUTPUT_DIR "results/results/giou/ciou_05l1" TEST.DETECTIONS_PER_IMAGE 3 DATASETS.TEST "('CVC_ColonDB', 'CVC_ClinicDB', 'ETIS_LaribPolypDB', 'CVC_VideoClinicDB_test', 'CVC_VideoClinicDB_valid')" MODEL.ROI_HEADS.LOSS_WEIGHTS   "(0.5,1.0,1.0)" MODEL.ROI_BOX_HEAD.USE_CIOU True
