_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("CVC_ClinicDB", "CVC_ColonDB", "CVC_HDClassif" )
  TEST: ("CVC_VideoClinicDB_test",)
INPUT:
  CROP:
    ENABLED: False
    SIZE: (0.7,0.9)
  COLOR_JITTER:
    ENABLED: True
    CONTRAST: (0.9,1.1)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (0, 2583, 4136) # (0, 10935, 17496)
  MAX_ITER: 5167
  LR_SCHEDULER_NAME: "WarmupCosineLR"

OUTPUT_DIR: "model_test"