_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    MIN_SIZE: 20
    MAX_SIZE: 175
  RPN:
    PRE_NMS_TOPK_TRAIN: 5000
    PRE_NMS_TOPK_TEST: 3000

  ROI_HEADS:
    SCORE_THRESH_TEST: 0.1

DATASETS:
  TRAIN: ("CVC_VideoClinicDB_train", )
#  TRAIN: ("CVC_ColonDB", "CVC_ClinicDB", )
  TEST: ("CVC_VideoClinicDB_valid","CVC_VideoClinicDB_test",)
INPUT:
  CROP:
    ENABLED: True
    SIZE: (0.8,0.8)
  HFLIP: True
  VFLIP: True
  COLOR_JITTER:
    ENABLED: True
    BRIGHTNESS: (0.9,1.1)
    SATURATION: (0.9,1.1)
    CONTRAST: (0.9,1.1)

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (0, 12287, 19656)
  MAX_ITER: 24575 # 5 epocas
#  STEPS: (0, 1140, 1824)
#  MAX_ITER: 2280 # 5 epocas
  LR_SCHEDULER_NAME: "WarmupCosineLR"

OUTPUT_DIR: "results/71_cj_clijic"

TEST:
  DETECTIONS_PER_IMAGE: 1
