_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("CVC-VideoClinicDBtrain_valid_train",)
  TEST: ("cvcvideoclinicdbtest_test",)
INPUT:
  CROP:
    ENABLED: True
    SIZE: (0.7,0.9)
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"

OUTPUT_DIR: "model_test"