MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/TridentNet/tridentnet_fast_R_50_C4_3x/148572287/model_final_e1027c.pkl"
  BACKBONE:
    NAME: "build_trident_resnet_backbone"
  ROI_HEADS:
    NAME: "TridentRes5ROIHeads"
    POSITIVE_FRACTION: 0.5
    BATCH_SIZE_PER_IMAGE: 128
    PROPOSAL_APPEND_GT: False
    NUM_CLASSES: 2
  PROPOSAL_GENERATOR:
    NAME: "TridentRPN"
  RPN:
    PRE_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TRAIN: 250
    POST_NMS_TOPK_TEST: 250
    NMS_THRESH: 0.7
    IOU_THRESHOLDS: [0.3, 0.8]
  TRIDENT:
    NUM_BRANCH: 3
    BRANCH_DILATIONS: [1, 2, 3]
    TEST_BRANCH_IDX: 1
    TRIDENT_STAGE: "res4"
VERSION: 2
SEED: 873