_BASE_: "clinic_test.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50

INPUT:
  CROP:
    ENABLED: True
    SIZE: (0.9, 0.9)
  HFLIP: True
  COLOR_JITTER:
    ENABLED: True
    PROB: 0.3
    BRIGHTNESS: (0.9,1.1)
    SATURATION: (0.9,1.1)
    CONTRAST: (0.9,1.1)
TEST:
  DETECTIONS_PER_IMAGE: 1

OUTPUT_DIR: "results/trident_da_adj"