_BASE_: "trainextra_test.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    MIN_SIZE: 10
    MAX_SIZE: 170
INPUT:
  CROP:
    ENABLED: True
    SIZE: (0.9, 0.9)
  HFLIP: True
  COLOR_JITTER:
    ENABLED: True
    PROB: 0.3
    BRIGHTNESS: (0.9,1.1)
    SATURATION: (0.9,1.1)
    CONTRAST: (0.9,1.1)
    HUE: (-.05,0.05)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  LR_SCHEDULER_NAME: "WarmupCosineLR"

OUTPUT_DIR: "results/extended_da_iousum"

TEST:
  DETECTIONS_PER_IMAGE: 1
