_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("CVC_VideoClinicDB_train", )
  TEST: ("CVC_VideoClinicDB_test","CVC_VideoClinicDB_valid",)
INPUT:
  CROP:
    ENABLED: False
  COLOR_JITTER:
    ENABLED: True
    BRIGHTNESS: (0.9,1.1)
    SATURATION: (0.9,1.1)
    CONTRAST: (0.9,1.1)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (0, 12287, 19656)
  MAX_ITER: 24575 # 5 epocas
  LR_SCHEDULER_NAME: "WarmupCosineLR"

OUTPUT_DIR: "results/color"
