_BASE_: "../Modified-RPN.yaml"
DATASETS:
  TRAIN: ("CVC_ClinicDB", "CVC_ColonDB", "CVC_HDClassif" )
  TEST: ("CVC_VideoClinicDB_test",)
MODEL:
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    MIN_SIZE: 10
    MAX_SIZE: 170
INPUT:
  HFLIP: True
  VFLIP: True
  ROTATION: True
  ROTATION_ANGLES: (-5,5)
  MIN_SIZE_TRAIN: (288, 384, )
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 288
  MAX_SIZE_TEST: 800
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (0, 2674, 4828)
  MAX_ITER: 5348 # 5 epocas
  LR_SCHEDULER_NAME: "WarmupCosineLR"

OUTPUT_DIR: "results/mod_rpn/faster/hd_da"
TEST:
  DETECTIONS_PER_IMAGE: 1
