_BASE_: "../Base-RCNN-FPN.yaml"
DATASETS:
  TRAIN: ("CVC_ClinicDB", "CVC_ColonDB", "CVC_HDClassif" )
  TEST: ("CVC_VideoClinicDB_test",)
MODEL:
  MASK_ON: False
  RESNETS:
    DEPTH: 50
#  PROPOSAL_GENERATOR:
#    MIN_SIZE: 10
#    MAX_SIZE: 170
INPUT:
#  CROP:
#    ENABLED: True
#    SIZE: (0.9, 0.9)
#  HFLIP: True
#  VFLIP: True
#  COLOR_JITTER:
#    ENABLED: True
#    PROB: 0.3
#    BRIGHTNESS: (0.9,1.1)
#    SATURATION: (0.9,1.1)
#    CONTRAST: (0.9,1.1)
#    HUE: (-.05,0.05)
  MIN_SIZE_TRAIN: (288, )
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 288
  MAX_SIZE_TEST: 800
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
#  STEPS: (0, 2674, 4828)
#  MAX_ITER: 5348 # 5 epocas
#  LR_SCHEDULER_NAME: "WarmupCosineLR"
  STEPS: (0, 5348, 9656)
  MAX_ITER: 10696 # 5 epocas
  LR_SCHEDULER_NAME: "WarmupCosineLR"
OUTPUT_DIR: "results/ablation/faster_hd_none"
TEST:
  DETECTIONS_PER_IMAGE: 1
